// All user-facing texts. Slovak, sentence case, informal "ty", active verbs.
// A button says what happens; the confirmation reuses the same verb.
export const copy = {
  common: {
    loading: 'Načítavam',
    retry: 'Skúsiť znova',
    cancel: 'Zrušiť',
    close: 'Zavrieť',
    back: 'Späť',
    save: 'Uložiť',
    saving: 'Ukladám',
    copy: 'Skopírovať',
    copied: 'Skopírované',
    share: 'Zdieľať',
    shareWhatsapp: 'Zdieľať na WhatsApp',
    writeWhatsapp: 'Napísať na WhatsApp',
    openWhatsappGroup: 'Otvoriť skupinu na WhatsAppe',
    optional: 'nepovinné',
    you: 'ty',
    errorTitle: 'Nepodarilo sa načítať údaje',
    offline: 'Si offline. Na načítanie termínov a platieb potrebuješ pripojenie.',
    notFoundTitle: 'Táto stránka neexistuje',
    notFoundBody: 'Odkaz je možno neúplný alebo starý.',
    goHome: 'Prejsť domov',
  },
  nav: {
    home: 'Domov',
    marketplace: 'Burza',
    finance: 'Financie',
    profile: 'Profil',
    groups: 'Partičky',
    switchGroup: 'Prepnúť partičku',
    createGroup: 'Založiť partičku',
    mainNavigation: 'Hlavná navigácia',
  },
  auth: {
    title: 'Prihlás sa',
    intro: 'Pošleme ti 6-miestny kód na e-mail. Heslo nepotrebuješ.',
    email: 'E-mail',
    emailPlaceholder: 'meno@example.sk',
    emailInvalid: 'Zadaj platný e-mail.',
    sendCode: 'Poslať kód',
    sendingCode: 'Posielam kód',
    codeTitle: 'Zadaj kód z e-mailu',
    codeSentTo: (email: string) => `Kód sme poslali na ${email}. Platí jednu hodinu.`,
    code: 'Kód',
    codeInvalid: 'Kód má 6 číslic.',
    signIn: 'Prihlásiť sa',
    signingIn: 'Prihlasujem',
    resend: 'Poslať nový kód',
    resent: 'Nový kód je na ceste',
    changeEmail: 'Zmeniť e-mail',
    signOut: 'Odhlásiť sa z appky',
    quickLoginTitle: 'Rýchle prihlásenie',
    quickLoginHint: 'Len pri vývoji. Seed používatelia s heslom hokej123.',
  },
  onboarding: {
    title: 'Vitaj na ľade',
    intro: 'Povedz nám, kto si. Spoluhráči ťa uvidia na súpiske.',
    submit: 'Pokračovať',
  },
  profile: {
    title: 'Profil',
    fullName: 'Meno a priezvisko',
    fullNameInvalid: 'Zadaj meno aj priezvisko.',
    nickname: 'Prezývka',
    jerseyNumber: 'Číslo dresu',
    jerseyInvalid: 'Číslo dresu musí byť od 0 do 99.',
    phone: 'Telefón',
    phoneHint: 'Admin ti môže napísať na WhatsApp.',
    phoneInvalid: 'Zadaj číslo ako 0905 123 456 alebo +421 905 123 456.',
    preferredRole: 'Zvyčajne hrávam',
    skater: 'V poli',
    goalie: 'V bráne',
    iban: 'IBAN',
    ibanHint: 'Potrebujú ho brankári, aby im partička mohla poslať odmenu. Ostatní ho nevidia.',
    ibanInvalid: 'IBAN nie je platný. Skontroluj ho.',
    saved: 'Profil uložený',
    save: 'Uložiť profil',
    theme: 'Vzhľad',
    themeSystem: 'Podľa systému',
    themeLight: 'Svetlý',
    themeDark: 'Tmavý',
    account: 'Účet',
    signedInAs: (email: string) => `Prihlásený ako ${email}`,
    superadmin: 'Prehľad partičiek',
  },
  groups: {
    createTitle: 'Založiť partičku',
    createIntro: 'Budeš jej adminom. Hráči budú platiť na účet, ktorý tu zadáš.',
    name: 'Názov partičky',
    namePlaceholder: 'Štvrtková partička Nitra',
    city: 'Mesto',
    country: 'Krajina',
    countrySk: 'Slovensko (€)',
    countryCz: 'Česko (Kč)',
    iban: 'IBAN účtu partičky',
    accountHolder: 'Majiteľ účtu',
    accountHolderHint: 'Meno, ktoré uvidia hráči ako príjemcu platby.',
    whatsapp: 'Odkaz na WhatsApp skupinu',
    whatsappHint: 'V skupine: Informácie o skupine, Pozvať cez odkaz.',
    whatsappInvalid: 'Odkaz musí začínať https://chat.whatsapp.com/',
    defaultsTitle: 'Predvolené hodnoty termínov',
    defaultsHint: 'Pri každom termíne ich môžeš zmeniť.',
    create: 'Založiť partičku',
    created: 'Partička založená',
    tabs: { sessions: 'Termíny', members: 'Členovia', finance: 'Financie', settings: 'Nastavenia' },
    invite: 'Pozvať hráčov',
    inviteTitle: 'Pozvi hráčov',
    inviteBody: 'Pošli odkaz do skupiny. Kto ho otvorí a prihlási sa, stane sa členom partičky.',
    inviteLink: 'Pozývací odkaz',
    inviteShareText: (groupName: string, url: string) => `Pridaj sa do partičky ${groupName} 🏒\n${url}`,
    regenerate: 'Vytvoriť nový odkaz',
    regenerateConfirmTitle: 'Vytvoriť nový pozývací odkaz?',
    regenerateConfirmBody: 'Starý odkaz prestane platiť. Členovia, ktorí už sú v partičke, v nej zostanú.',
    regenerated: 'Nový odkaz je pripravený',
    emptyTitle: 'Partička je pripravená',
    emptyBody: 'Vypíš prvý termín ľadu a pozvi hráčov cez odkaz.',
    noGroupsTitle: 'Zatiaľ nie si v žiadnej partičke',
    noGroupsBody: 'Popýtaj admina o pozývací odkaz, alebo založ vlastnú partičku. Voľné miesta nájdeš aj v burze.',
    settingsTitle: 'Nastavenia partičky',
    settingsSaved: 'Nastavenia uložené',
    roundingStep: 'Zaokrúhľovať cenu nahor na',
    members: {
      title: 'Členovia',
      admin: 'Admin',
      member: 'Člen',
      guest: 'Hosť',
      makeAdmin: 'Urobiť adminom',
      makeMember: 'Zmeniť na člena',
      remove: 'Odobrať z partičky',
      removeConfirmTitle: (name: string) => `Odobrať ${name} z partičky?`,
      removeConfirmBody: 'Jeho prihlásenia na termíny sa zrušia. Zostatok musí byť vyrovnaný.',
      removed: 'Člen odobratý',
      roleChanged: 'Rola zmenená',
      count: (n: number) => `${n} ${n === 1 ? 'člen' : n >= 2 && n <= 4 ? 'členovia' : 'členov'}`,
      contactAdmins: 'Kontakt na adminov',
      noPhone: 'Bez telefónu',
      actions: (name: string) => `Akcie pre ${name}`,
    },
  },
  invite: {
    title: 'Pozvánka do partičky',
    join: 'Pridať sa do partičky',
    joined: 'Si členom partičky',
    alreadyMember: 'Už si členom tejto partičky.',
    openGroup: 'Otvoriť partičku',
    invalidTitle: 'Pozvánka neplatí',
    invalidBody: 'Admin mohol vytvoriť nový odkaz. Popýtaj ho o aktuálny.',
    members: (n: number) => `${n} ${n === 1 ? 'člen' : n >= 2 && n <= 4 ? 'členovia' : 'členov'}`,
  },
  sessions: {
    upcomingTitle: 'Ďalšie termíny',
    pastTitle: 'Odohrané',
    nextSession: 'Najbližší termín',
    noUpcomingTitle: 'Žiadny vypísaný termín',
    noUpcomingBody: 'Keď admin vypíše ľad, uvidíš ho tu.',
    noUpcomingAdminBody: 'Vypíš ďalší termín, hráči sa naň hneď môžu prihlásiť.',
    create: 'Vypísať termín',
    createTitle: 'Nový termín',
    created: (n: number) => (n === 1 ? 'Termín vypísaný' : `Vypísaných ${n} termínov`),
    edit: 'Upraviť termín',
    editTitle: 'Upraviť termín',
    saved: 'Termín uložený',
    startsAt: 'Začiatok',
    duration: 'Dĺžka (minúty)',
    venue: 'Miesto',
    skaterCapacity: 'Hráči v poli',
    goalieSlots: 'Brankári',
    iceCost: 'Cena ľadu',
    goalieFee: 'Odmena brankára',
    pricingMode: 'Cena pre hráča',
    pricingDynamic: 'Delí sa náklad',
    pricingFixed: 'Fixná',
    pricingDynamicHint: 'Ľad a odmeny brankárov sa rozdelia medzi platiacich hráčov a zaokrúhlia nahor.',
    pricePerSkater: 'Fixná cena pre hráča',
    cancellationHours: 'Bezplatné odhlásenie (hodín pred začiatkom)',
    notes: 'Poznámka',
    repeat: 'Opakovať každý týždeň',
    repeatWeeks: 'Počet týždňov',
    status: {
      cancelled: 'Zrušený',
      completed: 'Uzavretý',
      started: 'Prebieha alebo čaká na uzávierku',
    },
    occupancy: (skaters: number, capacity: number, goalies: number, slots: number) =>
      `${skaters} z ${capacity} hráčov, ${goalies} z ${slots} ${slots === 1 ? 'brankára' : 'brankárov'}`,
    skatersShort: (n: number, cap: number) => `${n}/${cap}`,
    price: 'Cena',
    estimate: 'Odhad ceny',
    estimateNow: 'pri súčasnom počte',
    estimateFull: 'pri plnom ľade',
    estimateHint: 'Presná cena sa určí pri uzávierke podľa toho, koľko hráčov platí.',
    finalPrice: 'Výsledná cena',
    noPayers: 'Nikto neplatil, náklad zostáva na partičke.',
    freeCancellation: (phrase: string) => `Bezplatne sa odhlásiš ${phrase}.`,
    freeCancellationOver: 'Bezplatné odhlásenie už skončilo.',
    goalieFeeInfo: (fee: string) => `Brankár dostane ${fee}.`,
    myStatus: {
      confirmed: 'Si prihlásený',
      confirmedGoalie: 'Si prihlásený ako brankár',
      waitlist: (position: number) => `Si na čakacej listine, ${position}. v poradí`,
      pending: 'Čakáš na schválenie adminom',
      late_cancelled: 'Odhlásil si sa neskoro, zaplatíš ako keby si prišiel',
      none: 'Nie si prihlásený',
    },
    register: 'Prihlásiť sa na termín',
    registerGoalie: 'Prihlásiť sa ako brankár',
    registerWaitlist: 'Zapísať sa na čakaciu listinu',
    registered: 'Si prihlásený',
    registeredWaitlist: 'Si na čakacej listine',
    registeredPending: 'Žiadosť odoslaná, admin ju potvrdí',
    cancel: 'Odhlásiť sa',
    cancelled: 'Si odhlásený',
    cancelledLate: 'Si odhlásený. Ak sa na tvoje miesto nikto neprihlási, zaplatíš.',
    lateCancelTitle: 'Odhlásiť sa po termíne na bezplatné odhlásenie?',
    lateCancelBody: (price: string | null) =>
      price
        ? `Nikto nečaká na tvoje miesto, takže ho zaplatíš (približne ${price}), ak sa zaň nikto neprihlási.`
        : 'Nikto nečaká na tvoje miesto, takže ho zaplatíš, ak sa zaň nikto neprihlási.',
    lateCancelBodyGoalie: 'Brankári nič neplatia, ale partička zostane bez teba.',
    lateCancelWaitlist: 'Na tvoje miesto čaká ďalší hráč, preto neplatíš nič.',
    lateCancelConfirm: 'Odhlásiť sa aj tak',
    promotionTitle: 'Postúpil si z čakacej listiny',
    promotionBody: (when: string) => `Hráš ${when}. Ak nemôžeš, odhlás sa, nech miesto dostane ďalší.`,
    promotionAck: 'Rozumiem',
    lists: {
      skaters: 'Hráči v poli',
      goalies: 'Brankári',
      waitlist: 'Čakacia listina',
      pending: 'Hostia čakajú na schválenie',
      lateCancelled: 'Neskoro odhlásení (platia)',
      emptySkaters: 'Zatiaľ nikto. Buď prvý.',
      emptyGoalies: 'Brankár zatiaľ chýba.',
      guest: 'hosť',
      promoted: 'postúpil',
      unknownGuest: 'Hosť',
    },
    admin: {
      addPlayer: 'Pridať hráča',
      addPlayerTitle: 'Pridať hráča na termín',
      addPlayerHint: 'Napríklad keď sa ti ozval cez WhatsApp.',
      addAs: 'Pozícia',
      added: 'Hráč pridaný',
      searchMember: 'Hľadať člena',
      noMembersLeft: 'Všetci členovia sú už prihlásení.',
      remove: 'Odobrať z termínu',
      removeConfirmTitle: (name: string) => `Odobrať ${name} z termínu?`,
      removeConfirmBody: 'Neplatí nič. Ak niekto čaká, postúpi na jeho miesto.',
      removed: 'Registrácia odobratá',
      approve: 'Schváliť',
      approved: 'Hosť schválený',
      reject: 'Zamietnuť',
      rejected: 'Žiadosť zamietnutá',
      cancelSession: 'Zrušiť termín',
      cancelSessionTitle: 'Zrušiť celý termín?',
      cancelSessionBody: 'Všetky prihlásenia sa zrušia bez poplatku. Hráčom to oznám aj v skupine.',
      sessionCancelled: 'Termín zrušený',
      attendance: 'Dochádzka a uzávierka',
      reopen: 'Otvoriť termín znova',
      reopenTitle: 'Otvoriť uzavretý termín?',
      reopenBody: 'Všetky strhnuté sumy a odmeny brankárov sa vrátia. Potom opravíš dochádzku a termín znova uzavrieš.',
      reopened: 'Termín je znova otvorený',
      publish: 'Zverejniť v burze',
      published: 'Zverejnené v burze',
      unpublish: 'Stiahnuť z burzy',
      unpublished: 'Stiahnuté z burzy',
      contactGuest: 'Napísať hosťovi',
    },
  },
  attendance: {
    title: 'Dochádzka',
    intro: 'Označ, kto prišiel. Hráč v poli, ktorý neprišiel, platí aj tak.',
    came: 'Prišiel',
    missed: 'Neprišiel',
    summaryTitle: 'Súhrn uzávierky',
    payingSkaters: 'Platiaci hráči',
    lateCancelledIncluded: (n: number) => `z toho ${n} neskoro odhlásených`,
    price: 'Cena pre hráča',
    goaliesPaid: 'Brankári dostanú',
    iceCost: 'Ľad',
    result: 'Výsledok termínu',
    confirm: 'Uzavrieť termín',
    finalized: 'Termín uzavretý',
    notStarted: 'Dochádzku zapíšeš, keď termín začne.',
  },
  payments: {
    pay: 'Zaplatiť',
    payTitle: 'Zaplatiť do partičky',
    amountTitle: 'Koľko chceš poslať?',
    debt: (amount: string) => `Dlžíš ${amount}`,
    suggestedDebt: 'Vyrovnať dlh',
    suggestedNext: 'Najbližší termín (odhad)',
    topUp: 'Nabiť kredit',
    customAmount: 'Iná suma',
    continue: 'Pokračovať na platbu',
    qrTitle: 'Naskenuj QR v bankovej appke',
    qrHint: 'Na tomto telefóne QR nenaskenuješ. Skopíruj údaje nižšie do bankovej appky.',
    qrAlt: (amount: string, vs: string) => `QR kód platby ${amount}, variabilný symbol ${vs}`,
    iban: 'IBAN',
    recipient: 'Príjemca',
    amount: 'Suma',
    variableSymbol: 'Variabilný symbol',
    message: 'Správa pre príjemcu',
    iPaid: 'Zaplatil som',
    reported: 'Platba nahlásená. Admin ju potvrdí, keď príde na účet.',
    cancelPayment: 'Zrušiť platbu',
    paymentCancelled: 'Platba zrušená',
    pendingTitle: 'Rozpracované platby',
    showQr: 'Zobraziť QR',
    status: {
      pending: 'Čaká na zaplatenie',
      reported: 'Čaká na potvrdenie',
      confirmed: 'Potvrdená',
      rejected: 'Zamietnutá',
      cancelled: 'Zrušená',
    },
    invalidAmount: 'Zadaj sumu väčšiu ako nula, najviac s dvomi desatinnými miestami.',
  },
  finance: {
    title: 'Moje financie',
    balance: 'Zostatok',
    owes: (amount: string) => `Dlžíš ${amount}`,
    credit: (amount: string) => `Kredit ${amount}`,
    even: 'Máš vyrovnané',
    goalieOwed: (amount: string) => `Partička ti dlhuje ${amount}`,
    history: 'História',
    noHistory: 'Zatiaľ žiadne pohyby. Po prvom termíne alebo platbe ich uvidíš tu.',
    entry: {
      charge: (day: string) => `Termín ${day}`,
      lateCharge: (day: string) => `Termín ${day}, neskoré odhlásenie`,
      goalie_earning: (day: string) => `Odmena za termín ${day}`,
      topup: (vs: string) => `Platba VS ${vs}`,
      topupCash: 'Platba v hotovosti',
      goalie_payout: 'Vyplatená odmena',
      reversal: (day: string) => `Oprava termínu ${day}`,
      adjustment: (note: string) => `Oprava: ${note}`,
    },
    noGroups: 'Financie uvidíš, keď sa pridáš do partičky.',
  },
  groupFinance: {
    summary: 'Súhrn',
    collected: 'Vybrané spolu',
    paidOut: 'Vyplatené brankárom',
    iceTotal: 'Ľad spolu',
    cashAvailable: 'Hotovosť k dispozícii',
    debts: 'Dlhy hráčov',
    credits: 'Kredity a nároky',
    toConfirm: 'Platby na potvrdenie',
    toConfirmEmpty: 'Žiadna platba nečaká na potvrdenie.',
    search: 'Hľadať podľa VS alebo mena',
    confirm: 'Potvrdiť platbu',
    confirmed: 'Platba potvrdená',
    reject: 'Zamietnuť',
    rejectTitle: 'Zamietnuť platbu?',
    rejectBody: 'Použi, keď peniaze na účet neprišli. Hráčovi sa zostatok nezmení.',
    rejected: 'Platba zamietnutá',
    notReportedYet: 'nenahlásená',
    cash: 'Zapísať hotovosť',
    cashTitle: 'Zapísať platbu v hotovosti',
    cashMember: 'Kto platí',
    cashNote: 'Poznámka',
    cashRecorded: 'Hotovosť zapísaná',
    adjustment: 'Opraviť zostatok',
    adjustmentTitle: 'Opraviť zostatok',
    adjustmentHint: 'Kladná suma pridá kredit, záporná pridá dlh. Poznámku uvidí aj hráč.',
    adjustmentRecorded: 'Oprava zapísaná',
    goalies: 'Vyplatiť brankárov',
    goaliesEmpty: 'Partička nikomu nedlhuje odmenu.',
    payOut: 'Vyplatiť',
    payoutTitle: (name: string) => `Vyplatiť brankára ${name}`,
    payoutAmountHint: (max: string) => `Najviac ${max}.`,
    payoutNoIban: 'Brankár nemá v profile IBAN. Vyplať ho v hotovosti alebo ho popros, nech si IBAN doplní.',
    payoutCash: 'Vyplatiť v hotovosti',
    payoutTransfer: 'Vyplatiť prevodom',
    payoutPrepare: 'Pripraviť platbu',
    payoutDone: 'Vyplatené',
    payoutConfirmed: 'Brankár vyplatený',
    players: 'Hráči',
    playersColumns: { name: 'Meno', sessions: 'Termíny', paid: 'Zaplatené', charged: 'Strhnuté', balance: 'Zostatok' },
    remind: 'Pripomenúť na WhatsApp',
    sessionsTable: 'Termíny',
    sessionsColumns: {
      date: 'Dátum',
      skaters: 'Hráči',
      goalies: 'Brankári',
      charged: 'Strhnuté',
      ice: 'Ľad',
      goalieFees: 'Odmeny',
      result: 'Výsledok',
    },
    exportCsv: 'Stiahnuť CSV',
    sortBy: 'Zoradiť podľa',
  },
  marketplace: {
    title: 'Burza voľných miest',
    intro: 'Voľné miesta z partičiek, ktoré hľadajú hráčov alebo brankára.',
    city: 'Mesto',
    allCities: 'Všetky mestá',
    date: 'Od dátumu',
    role: 'Pozícia',
    anyRole: 'Všetko',
    skater: 'Pole',
    goalie: 'Brána',
    empty: 'Teraz nikto nehľadá hráčov. Skús zmeniť filtre alebo sa pozri neskôr.',
    freeSkaters: (n: number) => `${n} v poli`,
    freeGoalies: (n: number) => `${n} brankár${n === 1 ? '' : n <= 4 ? 'i' : 'ov'}`,
    approvalRequired: 'Admin schvaľuje hostí',
    yourGroup: 'Tvoja partička',
    open: 'Pozrieť termín',
    publishTitle: 'Zverejniť voľné miesta v burze',
    publishHint: 'Príspevok uvidia hráči z iných partičiek. Zmizne, keď sa miesta zaplnia alebo termín začne.',
    offerSkaters: 'Miesta v poli',
    offerGoalies: 'Miesta pre brankárov',
    requireApproval: 'Hostí schvaľujem',
    note: 'Poznámka k príspevku',
    publish: 'Zverejniť',
    publicTitle: (group: string) => `${group} hľadá hráčov`,
    publicLogin: 'Prihlásiť sa a zapísať',
    publicRegisterSkater: 'Prihlásiť sa do poľa',
    publicRegisterGoalie: 'Prihlásiť sa do brány',
    publicUnavailable: 'Miesta sú už obsadené alebo termín začal.',
    publicNotFound: 'Príspevok neexistuje alebo bol stiahnutý.',
    alreadyRegistered: 'Na tento termín už si prihlásený.',
    openSession: 'Otvoriť termín',
    guestPendingInfo: 'Admin tvoju žiadosť potvrdí. Kontakt na neho nájdeš v termíne.',
    price: 'Cena',
    priceApprox: 'približne',
    goalieFee: 'Odmena pre brankára',
  },
  superadmin: {
    title: 'Prehľad partičiek',
    columns: { name: 'Názov', city: 'Mesto', members: 'Členovia', sessions: 'Termíny' },
  },
} as const
